version: '3.7'

phases:
  install: 
    commands:
      - echo Installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - serverless deploy
  post_build:
    commands:
      - echo Build completed on `date`


  