version: '0.2'

phases:
  install: 
    commands:
      - echo Installing serverless
      - npm install -g serverless
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - serverless deploy
  post_build:
    commands:
      - echo Build completed on `date`


  